/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExhibitionRouteImport } from './routes/exhibition'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ParticipateRouteImport } from './routes/participate'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesHostedBuyerRouteImport } from './routes/programmes/hosted-buyer'
import { Route as ProgrammesStartupRouteImport } from './routes/programmes/startup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionRoute = ExhibitionRouteImport.update({
  id: '/exhibition',
  path: '/exhibition',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipateRoute = ParticipateRouteImport.update({
  id: '/participate',
  path: '/participate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesHostedBuyerRoute = ProgrammesHostedBuyerRouteImport.update({
  id: '/programmes/hosted-buyer',
  path: '/programmes/hosted-buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesStartupRoute = ProgrammesStartupRouteImport.update({
  id: '/programmes/startup',
  path: '/programmes/startup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/exhibition': typeof ExhibitionRoute
  '/faq': typeof FaqRoute
  '/participate': typeof ParticipateRoute
  '/privacy': typeof PrivacyRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/programmes/hosted-buyer': typeof ProgrammesHostedBuyerRoute
  '/programmes/startup': typeof ProgrammesStartupRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/exhibition': typeof ExhibitionRoute
  '/faq': typeof FaqRoute
  '/participate': typeof ParticipateRoute
  '/privacy': typeof PrivacyRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/programmes/hosted-buyer': typeof ProgrammesHostedBuyerRoute
  '/programmes/startup': typeof ProgrammesStartupRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/exhibition': typeof ExhibitionRoute
  '/faq': typeof FaqRoute
  '/participate': typeof ParticipateRoute
  '/privacy': typeof PrivacyRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/programmes/hosted-buyer': typeof ProgrammesHostedBuyerRoute
  '/programmes/startup': typeof ProgrammesStartupRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conference'
    | '/contact'
    | '/exhibition'
    | '/faq'
    | '/participate'
    | '/privacy'
    | '/sponsors'
    | '/terms'
    | '/programmes/hosted-buyer'
    | '/programmes/startup'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conference'
    | '/contact'
    | '/exhibition'
    | '/faq'
    | '/participate'
    | '/privacy'
    | '/sponsors'
    | '/terms'
    | '/programmes/hosted-buyer'
    | '/programmes/startup'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conference'
    | '/contact'
    | '/exhibition'
    | '/faq'
    | '/participate'
    | '/privacy'
    | '/sponsors'
    | '/terms'
    | '/programmes/hosted-buyer'
    | '/programmes/startup'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConferenceRoute: typeof ConferenceRoute
  ContactRoute: typeof ContactRoute
  ExhibitionRoute: typeof ExhibitionRoute
  FaqRoute: typeof FaqRoute
  ParticipateRoute: typeof ParticipateRoute
  PrivacyRoute: typeof PrivacyRoute
  SponsorsRoute: typeof SponsorsRoute
  TermsRoute: typeof TermsRoute
  ProgrammesHostedBuyerRoute: typeof ProgrammesHostedBuyerRoute
  ProgrammesStartupRoute: typeof ProgrammesStartupRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibition': {
      id: '/exhibition'
      path: '/exhibition'
      fullPath: '/exhibition'
      preLoaderRoute: typeof ExhibitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participate': {
      id: '/participate'
      path: '/participate'
      fullPath: '/participate'
      preLoaderRoute: typeof ParticipateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/hosted-buyer': {
      id: '/programmes/hosted-buyer'
      path: '/programmes/hosted-buyer'
      fullPath: '/programmes/hosted-buyer'
      preLoaderRoute: typeof ProgrammesHostedBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/startup': {
      id: '/programmes/startup'
      path: '/programmes/startup'
      fullPath: '/programmes/startup'
      preLoaderRoute: typeof ProgrammesStartupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConferenceRoute: ConferenceRoute,
  ContactRoute: ContactRoute,
  ExhibitionRoute: ExhibitionRoute,
  FaqRoute: FaqRoute,
  ParticipateRoute: ParticipateRoute,
  PrivacyRoute: PrivacyRoute,
  SponsorsRoute: SponsorsRoute,
  TermsRoute: TermsRoute,
  ProgrammesHostedBuyerRoute: ProgrammesHostedBuyerRoute,
  ProgrammesStartupRoute: ProgrammesStartupRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
